# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs) {
    .Call('kohonen_RcppBatchSupersom', PACKAGE = 'kohonen', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs)
}

CreateStdDistancePointers <- function(types, considerNaNs) {
    .Call('kohonen_CreateStdDistancePointers', PACKAGE = 'kohonen', types, considerNaNs)
}

CreateStdDistancePointer <- function(type, considerNaNs) {
    .Call('kohonen_CreateStdDistancePointer', PACKAGE = 'kohonen', type, considerNaNs)
}

ObjectDistances <- function(data, numVars, numNAs, distanceFunctions, weights) {
    .Call('kohonen_ObjectDistances', PACKAGE = 'kohonen', data, numVars, numNAs, distanceFunctions, weights)
}

RcppMap <- function(data, numVars, numNAs, codes, weights, distanceFunctions) {
    .Call('kohonen_RcppMap', PACKAGE = 'kohonen', data, numVars, numNAs, codes, weights, distanceFunctions)
}

RcppParallelBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores) {
    .Call('kohonen_RcppParallelBatchSupersom', PACKAGE = 'kohonen', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores)
}

RcppSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs) {
    .Call('kohonen_RcppSupersom', PACKAGE = 'kohonen', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs)
}

